services:
  - type: web
    name: market-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "24"
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
